FROM nginx:latest
RUN echo '<h1>Ola, iMundo!</h1><a href="about.html">About</a>' > /usr/share/nginx/html/index.html
RUN echo '<h1>Sobre...</h1><a href="index.html">Voltar</a>' > /usr/share/nginx/html/about.html
